import type { SlackSendRequest, SlackSendResult, SlackStatus } from "../../shared/contracts";
import type { SlackStore } from "./slackStore";

const MAX_RESPONSE_BYTES = 64 * 1024; const TIMEOUT_MS = 8_000;
export class SlackClient {
  constructor(private readonly store: SlackStore, private readonly fetcher: typeof fetch = fetch) {}
  async test(): Promise<SlackStatus> { const value = await this.call("auth.test", {}); if (typeof value.team !== "string" || typeof value.user !== "string") throw new Error("Slack returned an invalid authentication response"); return this.store.identify(value.team, value.user); }
  async send(input: unknown): Promise<SlackSendResult> { const request = parseSend(input); const value = await this.call("chat.postMessage", { channel: request.channel, text: request.text, ...(request.threadTimestamp ? { thread_ts: request.threadTimestamp } : {}), unfurl_links: false, unfurl_media: false }); if (typeof value.channel !== "string" || typeof value.ts !== "string") throw new Error("Slack returned an invalid message response"); return { channel: value.channel, timestamp: value.ts }; }
  private async call(method: "auth.test" | "chat.postMessage", body: Record<string, unknown>): Promise<Record<string, unknown>> { let response: Response; try { response = await this.fetcher(`https://slack.com/api/${method}`, { method: "POST", redirect: "error", headers: { authorization: `Bearer ${this.store.token()}`, "content-type": "application/json; charset=utf-8" }, body: JSON.stringify(body), signal: AbortSignal.timeout(TIMEOUT_MS) }); } catch { throw new Error("Slack request failed"); } if (!response.ok) throw new Error(`Slack request failed with HTTP ${response.status}`); const value = await boundedJson(response); if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("Slack returned an invalid response"); const row = value as Record<string, unknown>; if (row.ok !== true) throw new Error(`Slack rejected the request${typeof row.error === "string" && /^[a-z0-9_]+$/.test(row.error) ? `: ${row.error}` : ""}`); return row; }
}
function parseSend(value: unknown): SlackSendRequest { if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("Slack message is invalid"); const row = value as Record<string, unknown>; if (Object.keys(row).some((key) => !["channel", "text", "threadTimestamp"].includes(key)) || typeof row.channel !== "string" || !/^[A-Z][A-Z0-9]{1,31}$/.test(row.channel) || typeof row.text !== "string" || !row.text.trim() || row.text.length > 4_000 || /\0/.test(row.text) || (row.threadTimestamp !== undefined && (typeof row.threadTimestamp !== "string" || !/^\d{1,20}\.\d{1,20}$/.test(row.threadTimestamp)))) throw new Error("Slack message is invalid"); return { channel: row.channel, text: row.text.trim(), ...(row.threadTimestamp ? { threadTimestamp: row.threadTimestamp as string } : {}) }; }
async function boundedJson(response: Response): Promise<unknown> { const declared = Number(response.headers.get("content-length")); if (Number.isFinite(declared) && declared > MAX_RESPONSE_BYTES) throw new Error("Slack response exceeded 64 KB"); if (!response.body) throw new Error("Slack returned an empty response"); const reader = response.body.getReader(); const chunks: Uint8Array[] = []; let total = 0; try { while (true) { const { done, value } = await reader.read(); if (done) break; total += value.byteLength; if (total > MAX_RESPONSE_BYTES) { await reader.cancel(); throw new Error("Slack response exceeded 64 KB"); } chunks.push(value); } } finally { reader.releaseLock(); } const bytes = new Uint8Array(total); let offset = 0; for (const chunk of chunks) { bytes.set(chunk, offset); offset += chunk.byteLength; } try { return JSON.parse(new TextDecoder().decode(bytes)); } catch { throw new Error("Slack returned invalid JSON"); } }
