import type { MessageCatalog } from "../i18n";
const messages = {
  locale: "لغة الواجهة", help: "يستخدم OrbiAgents اللغة المحددة هنا فقط ولا يقرأ لغة نظام التشغيل.", subtitle: "مركز قيادة محلي · قياس تشغيل موثّق", active: "نشط", hire: "توظيف وكيل",
  commandCenter: "مركز القيادة", operate: "تشغيل", coordinate: "تنسيق", observe: "مراقبة", system: "النظام", floor: "الساحة", terminals: "الطرفيات", files: "الملفات", repository: "المستودع", tasks: "المهام", messages: "الرسائل", approvals: "الموافقات", memory: "الذاكرة", skills: "المهارات", activity: "النشاط", costs: "التكاليف", recovery: "الاستعادة", workspaces: "مساحات العمل", settings: "الإعدادات", updates: "التحديثات", setup: "التهيئة",
  hireTitle: "توظيف وكيل مداري", fleetConfiguration: "إعداد الأسطول", configureSpecialist: "إعداد وكيل متخصص", profileRetention: "يتم التحقق من الملفات وحفظها مع جلسة الوكيل المحلية.", importHire: "استيراد التوظيف", copyHire: "نسخ التوظيف", close: "إغلاق", localGallery: "معرض الوكلاء المحلي", role: "الدور", generalist: "عام", generalistDetail: "تنفيذ متوازن", planner: "مخطط", plannerDetail: "تقسيم المهام", builder: "منفذ", builderDetail: "تنفيذ التغييرات", reviewer: "مراجع", reviewerDetail: "تدقيق وتحقق", researcher: "باحث", researcherDetail: "فحص الأدلة",
  callSign: "الاسم الرمزي", agentName: "اسم الوكيل", runtime: "بيئة التشغيل", agentRuntime: "بيئة تشغيل الوكيل", workspace: "مساحة العمل", workspacePath: "مسار مساحة عمل الوكيل", workspacePlaceholder: "/المسار/المطلق/للمشروع", timebox: "المدة", planningTimebox: "مدة تخطيط الوكيل", minutes30: "30 دقيقة", hour1: "ساعة واحدة", hours2: "ساعتان", hours4: "4 ساعات", missionGoal: "هدف المهمة", missionGoalLabel: "هدف مهمة الوكيل", missionGoalPlaceholder: "صف النتيجة التي يمتلكها هذا الوكيل", capabilities: "القدرات", planning: "تخطيط", coding: "برمجة", review: "مراجعة", research: "بحث", testing: "اختبار", signalColor: "لون الإشارة", cyan: "سماوي", violet: "بنفسجي", green: "أخضر", gold: "ذهبي", rose: "وردي", isolatedWorktree: "شجرة عمل معزولة", useIsolatedWorktree: "استخدام شجرة عمل معزولة", launching: "جارٍ التشغيل…", launchAgent: "تشغيل الوكيل", roleSuffix: "دور", capabilitySuffix: "قدرة", colorSuffix: "لون إشارة", hireLinkImported: "تم استيراد رابط التوظيف. راجعه واختر مساحة عمل قبل التشغيل.", hireLinkCopied: "تم نسخ رابط التوظيف. لا يتم تضمين مسارات العمل أو بيانات الاعتماد.", profileImported: "تم استيراد الملف. راجعه واختر مساحة عمل قبل التشغيل.", profileSelected: "تم اختيار الملف. راجعه قبل التشغيل.",
  commandComposer: "محرر أوامر الوكيل", command: "الأمر", agentCommand: "أمر الوكيل", sendInstruction: "إرسال تعليمات إلى", selectRunningAgent: "اختر وكيلاً قيد التشغيل", queue: "إضافة للطابور", workspaceAttachment: "مرفق من مساحة العمل", attachWorkspaceFile: "إرفاق ملف من مساحة العمل…", attach: "إرفاق", remove: "إزالة", queuedEncrypted: "في الطابور · استئناف محلي مشفر", sending: "جارٍ الإرسال…", sendAll: "إرسال الكل", filesCount: "ملفات", retry: "إعادة المحاولة", send: "إرسال",
  agentRoster: "قائمة الوكلاء", agentFleet: "أسطول الوكلاء", registered: "مسجل", emptyFleet: "شغّل وكيلك الأول لملء منصة القيادة.", workspaceSuffix: "مساحة عمل", agentActivity: "نشاط الوكيل", signalLog: "سجل الإشارات", liveTelemetry: "قياس مباشر", emptySignals: "ستظهر إشارات التشغيل هنا.",
} satisfies MessageCatalog;
export default messages;
