import type { MessageCatalog } from "../i18n";
const messages = {
  locale: "界面语言", help: "OrbiAgents 仅使用此处选择的语言，不读取操作系统语言。", subtitle: "本地智能体指挥台 · 已验证的运行遥测", active: "运行中", hire: "聘用智能体",
  commandCenter: "指挥中心", operate: "操作", coordinate: "协作", observe: "监控", system: "系统", floor: "总览", terminals: "终端", files: "文件", repository: "代码仓库", tasks: "任务", messages: "消息", approvals: "审批", memory: "记忆", skills: "技能", activity: "活动", costs: "成本", recovery: "恢复", workspaces: "工作区", settings: "设置", updates: "更新", setup: "配置",
  hireTitle: "聘用轨道智能体", fleetConfiguration: "团队配置", configureSpecialist: "配置专用智能体", profileRetention: "配置会经过验证并保存在本地智能体会话中。", importHire: "导入聘用配置", copyHire: "复制聘用配置", close: "关闭", localGallery: "本地智能体模板", role: "角色", generalist: "通用型", generalistDetail: "均衡执行", planner: "规划者", plannerDetail: "拆解任务", builder: "构建者", builderDetail: "实现变更", reviewer: "审查者", reviewerDetail: "审计并验证", researcher: "研究者", researcherDetail: "调查证据",
  callSign: "代号", agentName: "智能体名称", runtime: "运行时", agentRuntime: "智能体运行时", workspace: "工作区", workspacePath: "智能体工作区路径", workspacePlaceholder: "/项目的/绝对路径", timebox: "时间限制", planningTimebox: "智能体规划时间限制", minutes30: "30 分钟", hour1: "1 小时", hours2: "2 小时", hours4: "4 小时", missionGoal: "任务目标", missionGoalLabel: "智能体任务目标", missionGoalPlaceholder: "描述此智能体负责的成果", capabilities: "能力", planning: "规划", coding: "编码", review: "审查", research: "研究", testing: "测试", signalColor: "标识颜色", cyan: "青色", violet: "紫色", green: "绿色", gold: "金色", rose: "玫红", isolatedWorktree: "隔离工作树", useIsolatedWorktree: "使用隔离工作树", launching: "正在启动…", launchAgent: "启动智能体", roleSuffix: "角色", capabilitySuffix: "能力", colorSuffix: "标识颜色", hireLinkImported: "聘用链接已导入。请检查并在启动前选择工作区。", hireLinkCopied: "聘用链接已复制，其中不会包含工作区路径或凭据。", profileImported: "配置已导入。请检查并在启动前选择工作区。", profileSelected: "配置已选择，请在启动前检查。",
  commandComposer: "智能体命令编辑器", command: "命令", agentCommand: "智能体命令", sendInstruction: "发送指令给", selectRunningAgent: "选择运行中的智能体", queue: "加入队列", workspaceAttachment: "工作区文件附件", attachWorkspaceFile: "附加工作区文件…", attach: "附加", remove: "移除", queuedEncrypted: "个已排队 · 本地加密恢复", sending: "正在发送…", sendAll: "全部发送", filesCount: "个文件", retry: "重试", send: "发送",
  agentRoster: "智能体名册", agentFleet: "智能体团队", registered: "个已注册", emptyFleet: "启动第一个智能体以填充指挥台。", workspaceSuffix: "工作区", agentActivity: "智能体活动", signalLog: "信号日志", liveTelemetry: "实时遥测", emptySignals: "运行信号将显示在此处。",
  selectAgentRepository: "选择智能体以检查其工作区代码仓库。", githubIngestion: "GitHub 议题与 CI 数据", repositoryOperations: "代码仓库操作", inspectLocalGit: "检查本地 Git", checkGithubAuth: "检查 GitHub 登录", refreshGithub: "刷新 GitHub", localGitPolicy: "本地 Git 检查只读且有界，不会暂存、提交、切换分支或推送。", noUpstream: "无上游", ahead: "领先", behind: "落后", changesCount: "项变更", workingChanges: "工作区变更", cleanTree: "工作树干净。", recentCommits: "最近提交", noCommits: "未加载提交。", changesTruncated: "工作区变更已限制为 200 项。", inspectGitPrompt: "检查本地 Git 以加载分支、变更和提交信息。", githubPolicy: "只读并由操作者触发。使用本地已登录的 gh CLI，不传递令牌、不自动登录、不轮询，也不修改工作流。", githubAuthenticated: "GitHub CLI 已在本地登录。", githubUnauthenticated: "GitHub CLI 尚未登录。请在终端运行 gh auth login。", githubMissing: "未安装 GitHub CLI。", fetched: "获取于", boundedGithub: "最多 50 个议题和 30 次运行", openIssuesCount: "个开放议题", recentRunsCount: "次最近运行", activeRunsCount: "次活动", attentionRunsCount: "次非成功完成", showing: "显示", issuesCount: "个议题", runsCount: "次运行", filterIssues: "按标签筛选议题", allLabels: "所有已加载标签", filterRuns: "筛选工作流运行", allRuns: "所有最近运行", successful: "成功", nonSuccess: "非成功完成", openIssues: "开放议题", noLabels: "无标签", noMatchingIssues: "没有已加载的议题符合此标签。", recentActionRuns: "最近 Actions 运行", pending: "等待中", noMatchingRuns: "没有已加载的运行符合此状态。", githubRefreshPrompt: "检查登录状态，然后明确刷新所选代码仓库。",
  welcome: "欢迎使用 OrbiAgents", setupPrerequisites: "设置与先决条件", systemReadiness: "系统就绪状态", orbiSetup: "OrbiAgents 设置", rerunChecks: "重新检查", setupPolicy: "这些检查只会查看可执行文件访问和平台能力。OrbiAgents 不会安装软件、更改 PATH、登录账户或阻止使用指挥中心。", prerequisitesReady: "核心先决条件已就绪。", prerequisitesMissing: "缺少部分核心先决条件。", required: "必需", optional: "可选", continueOrbi: "继续使用 OrbiAgents", continueMissing: "在缺少工具时继续", lastChecked: "上次检查", onboardingAcknowledged: "已确认引导",
  startupRecovery: "启动恢复", readOnlyInventory: "只读清单", recoveryReport: "启动恢复报告", refreshReport: "刷新报告", recoveryPolicy: "只读清单。恢复功能不会重启命令、交付任务、更改工作树或决定审批。", loadingRecovery: "正在加载恢复报告…", needReview: "项需要检查。", reportTruncated: "有界报告已截断。", noRecoveryItems: "未检测到中断的会话或未完成的持久工作。", inventoryGenerated: "清单生成于",
  orbiHive: "Orbi Hive", selectHive: "选择或启动智能体以打开其项目 Hive。", hiveOperatorPanel: "Orbi Hive 操作面板", refresh: "刷新", approvalReason: "批准原因", rejectionReason: "拒绝原因", completedResult: "已完成任务的结果", taskTitle: "任务标题", taskForPrime: "交给 Orbi-Prime 的任务", taskDetails: "任务详情", assignedAgent: "已分配的项目智能体", selectProjectAgent: "选择项目智能体", assignPrime: "通过 Orbi-Prime 分配", approvalsTitle: "审批", approve: "批准", reject: "拒绝", noApprovals: "没有审批。", primeInbox: "Prime 收件箱", noMessages: "没有消息。", blackboard: "共享黑板", noSharedResults: "没有共享结果。", taskOperations: "任务操作", total: "总计", actionable: "可执行", blockedCount: "受阻", waitingDependencies: "等待依赖", completedCount: "已完成", failedCount: "失败", retriedCount: "已重试", noTasksAssigned: "尚未分配任务", queuedColumn: "排队", activeColumn: "活动", blockedColumn: "受阻", doneColumn: "完成", tasksSuffix: "任务", unassigned: "未分配", attempt: "尝试", start: "开始", block: "阻塞", complete: "完成", noTasks: "没有任务", healthFailed: "失败 — 需要检查", healthBlocked: "受阻 — 需要操作者处理", healthWaiting: "正在等待依赖", healthRetry: "重试", healthCompleted: "已完成", healthRunning: "运行中", healthReady: "就绪", noDependencies: "无依赖", dependenciesUnresolved: "个依赖未解决", dependenciesComplete: "个依赖已完成", of: "/",
  applicationUpdates: "应用更新", installed: "已安装", loading: "正在加载", orbiUpdates: "OrbiAgents 更新", updatePolicy: "更新由操作者控制。OrbiAgents 不会静默检查、下载或重启；当智能体、审批、任务或保留工作区需要处理时，重启会安全失败。", version: "版本", checking: "正在检查…", checkUpdates: "检查更新", downloading: "正在下载…", download: "下载", restartInstall: "重启并安装", updateReading: "正在读取更新状态…", updateReadyCheck: "可以检查更新", updateCheckingReleases: "正在检查 GitHub 版本…", updateAvailable: "有可用更新", updateCurrent: "已是最新版本", updateDownloadingPackage: "正在下载版本包…", updateReadyInstall: "更新已可安装", updateFailed: "更新操作失败",
  operatorApprovals: "操作者审批", noProjectApprovals: "此项目没有审批请求。", applyWorkspaceConfirm: "将所选文件应用到干净的源代码仓库吗？", discardWorkspaceConfirm: "永久丢弃此保留工作树及其所有未合并变更吗？", preservedChanges: "保留的工作区变更", changesPreserved: "变更已保留以供检查", recoveryDetailsMissing: "已在重启后恢复，但无法自动刷新变更详情。", applyTrackedFile: "应用已跟踪文件", applyNewFile: "应用新文件", tracked: "已跟踪", newFile: "新文件", applySelected: "应用所选项", discardWorktree: "丢弃工作树",
  installedSkills: "已安装技能", discovered: "个已发现", installedAgentSkills: "已安装的智能体技能", searchSkills: "搜索技能", searchInstalledSkills: "搜索已安装技能", skillsPlaceholder: "测试、Android、安全…", source: "来源", filterSkillsSource: "按来源筛选技能", allSources: "所有来源", scanning: "正在扫描…", search: "搜索", reset: "重置", skillsPolicy: "浏览只读取有界的前置元数据，绝不执行技能指令。移除需要确认，且只会把重新验证的已安装技能目录移至系统废纸篓。", moveTrash: "移至废纸篓", scanningSkills: "正在扫描已安装技能…", noSkillsMatch: "没有已安装技能符合此搜索。", removeSkillPrefix: "将已安装技能", removeSkillSuffix: "移至废纸篓吗？",
  projectMemory: "项目记忆", selectProjectMemory: "选择智能体以打开其项目记忆。", markdownMemory: "项目 Markdown 记忆", memoryTitle: "记忆标题", memoryContent: "记忆内容", memoryContentPlaceholder: "已验证的决定、结果或可复用上下文", capture: "记录", searchProjectMemory: "搜索项目记忆", searchLocalMemory: "搜索本地记忆", clear: "清除", noMemoryResults: "没有结果：", noProjectMemories: "尚未记录项目记忆", resultsFor: "个结果：", projectMemories: "条项目记忆", sourcesCount: "个来源", condensed: "条已压缩", knowledgeMap: "知识图谱", verifiedRelationships: "条已验证文本关联", sharedConcepts: "共享概念", noRelationships: "记录相关项目记忆以显示确定性连接。",
  normalizedActivity: "标准化运行活动", clearFilters: "清除筛选", noSessionSignals: "此桌面会话没有运行信号", signals: "个信号", agentsCount: "个智能体", providerEvents: "个提供方事件", needAttention: "个需要处理", filterActivityAgent: "按智能体筛选活动", allAgents: "所有智能体", filterActivitySource: "按来源筛选活动", filterActivityState: "按状态筛选活动", allStates: "所有状态", noSignalMatches: "没有信号符合这些筛选条件。",
  usageCosts: "用量与成本控制", measuredTelemetry: "实测会话遥测", refreshLedger: "刷新账本", providerSignals: "个提供方信号", agentMinutes: "智能体分钟", allSignals: "个全部信号", telemetryPolicy: "会话遥测只统计已净化的运行信号和智能体运行时长。提供方没有在此公开一致的令牌或工具总数，因此 OrbiAgents 不会虚构数据。", observedWork: "观测到的工作", noProviderActivity: "此桌面会话尚未测量到提供方活动。", estimatePolicy: "仅限操作者在本地授权的估算。这些数值不是令牌测量、提供方账单或实际费用。", ledgerCorrupt: "账本完整性不确定。当前仅显示已验证前缀，并阻止新增成本记录。", ledgerEstimate: "是全部已验证记录的账本授权估算。", noCostAuthorizations: "没有已验证的成本授权", verifiedEntries: "条已验证记录", projectsCount: "个项目", visibleEstimate: "可见估算", boundedSet: "最新有界集合", project: "项目", filterCostsProject: "按项目筛选成本", allLoadedProjects: "所有已加载项目", approvedEstimate: "操作者批准的估算", mission: "任务", run: "运行", noCostMatches: "没有已加载记录符合此项目。", costTruncated: "仅显示最新 200 条已验证记录；上方账本总额包含完整的已验证链。", loadingLedger: "正在加载成本账本…",
  runtimeAdapters: "运行时适配器", adapterPolicy: "自定义适配器是明确的本地允许列表条目。可执行文件必须使用绝对路径；参数不经 shell 而按原样传递。不支持密钥或环境覆盖。", adapterId: "适配器标识符", adapterName: "适配器显示名称", displayName: "显示名称", adapterPath: "适配器可执行文件路径", executablePlaceholder: "/可执行文件的/绝对路径", adapterArguments: "适配器参数，每行一个", argumentsPlaceholder: "每行一个原样参数（可选）", addAdapter: "添加允许的适配器", builtIn: "内置", customAllowlisted: "自定义允许项",
} satisfies MessageCatalog;
export default messages;
