import type { MessageCatalog } from "../i18n";
const messages = {
  locale: "界面语言", help: "OrbiAgents 仅使用此处选择的语言，不读取操作系统语言。", subtitle: "本地智能体指挥台 · 已验证的运行遥测", active: "运行中", hire: "聘用智能体",
  commandCenter: "指挥中心", operate: "操作", coordinate: "协作", observe: "监控", system: "系统", floor: "总览", terminals: "终端", files: "文件", repository: "代码仓库", tasks: "任务", messages: "消息", approvals: "审批", memory: "记忆", skills: "技能", activity: "活动", costs: "成本", recovery: "恢复", workspaces: "工作区", settings: "设置", updates: "更新", setup: "配置",
  hireTitle: "聘用轨道智能体", fleetConfiguration: "团队配置", configureSpecialist: "配置专用智能体", profileRetention: "配置会经过验证并保存在本地智能体会话中。", importHire: "导入聘用配置", copyHire: "复制聘用配置", close: "关闭", localGallery: "本地智能体模板", role: "角色", generalist: "通用型", generalistDetail: "均衡执行", planner: "规划者", plannerDetail: "拆解任务", builder: "构建者", builderDetail: "实现变更", reviewer: "审查者", reviewerDetail: "审计并验证", researcher: "研究者", researcherDetail: "调查证据",
  callSign: "代号", agentName: "智能体名称", runtime: "运行时", agentRuntime: "智能体运行时", workspace: "工作区", workspacePath: "智能体工作区路径", workspacePlaceholder: "/项目的/绝对路径", timebox: "时间限制", planningTimebox: "智能体规划时间限制", minutes30: "30 分钟", hour1: "1 小时", hours2: "2 小时", hours4: "4 小时", missionGoal: "任务目标", missionGoalLabel: "智能体任务目标", missionGoalPlaceholder: "描述此智能体负责的成果", capabilities: "能力", planning: "规划", coding: "编码", review: "审查", research: "研究", testing: "测试", signalColor: "标识颜色", cyan: "青色", violet: "紫色", green: "绿色", gold: "金色", rose: "玫红", isolatedWorktree: "隔离工作树", useIsolatedWorktree: "使用隔离工作树", launching: "正在启动…", launchAgent: "启动智能体", roleSuffix: "角色", capabilitySuffix: "能力", colorSuffix: "标识颜色", hireLinkImported: "聘用链接已导入。请检查并在启动前选择工作区。", hireLinkCopied: "聘用链接已复制，其中不会包含工作区路径或凭据。", profileImported: "配置已导入。请检查并在启动前选择工作区。", profileSelected: "配置已选择，请在启动前检查。",
  commandComposer: "智能体命令编辑器", command: "命令", agentCommand: "智能体命令", sendInstruction: "发送指令给", selectRunningAgent: "选择运行中的智能体", queue: "加入队列", workspaceAttachment: "工作区文件附件", attachWorkspaceFile: "附加工作区文件…", attach: "附加", remove: "移除", queuedEncrypted: "个已排队 · 本地加密恢复", sending: "正在发送…", sendAll: "全部发送", filesCount: "个文件", retry: "重试", send: "发送",
  agentRoster: "智能体名册", agentFleet: "智能体团队", registered: "个已注册", emptyFleet: "启动第一个智能体以填充指挥台。", workspaceSuffix: "工作区", agentActivity: "智能体活动", signalLog: "信号日志", liveTelemetry: "实时遥测", emptySignals: "运行信号将显示在此处。",
  selectAgentRepository: "选择智能体以检查其工作区代码仓库。", githubIngestion: "GitHub 议题与 CI 数据", repositoryOperations: "代码仓库操作", inspectLocalGit: "检查本地 Git", checkGithubAuth: "检查 GitHub 登录", refreshGithub: "刷新 GitHub", localGitPolicy: "本地 Git 检查只读且有界，不会暂存、提交、切换分支或推送。", noUpstream: "无上游", ahead: "领先", behind: "落后", changesCount: "项变更", workingChanges: "工作区变更", cleanTree: "工作树干净。", recentCommits: "最近提交", noCommits: "未加载提交。", changesTruncated: "工作区变更已限制为 200 项。", inspectGitPrompt: "检查本地 Git 以加载分支、变更和提交信息。", githubPolicy: "只读并由操作者触发。使用本地已登录的 gh CLI，不传递令牌、不自动登录、不轮询，也不修改工作流。", githubAuthenticated: "GitHub CLI 已在本地登录。", githubUnauthenticated: "GitHub CLI 尚未登录。请在终端运行 gh auth login。", githubMissing: "未安装 GitHub CLI。", fetched: "获取于", boundedGithub: "最多 50 个议题和 30 次运行", openIssuesCount: "个开放议题", recentRunsCount: "次最近运行", activeRunsCount: "次活动", attentionRunsCount: "次非成功完成", showing: "显示", issuesCount: "个议题", runsCount: "次运行", filterIssues: "按标签筛选议题", allLabels: "所有已加载标签", filterRuns: "筛选工作流运行", allRuns: "所有最近运行", successful: "成功", nonSuccess: "非成功完成", openIssues: "开放议题", noLabels: "无标签", noMatchingIssues: "没有已加载的议题符合此标签。", recentActionRuns: "最近 Actions 运行", pending: "等待中", noMatchingRuns: "没有已加载的运行符合此状态。", githubRefreshPrompt: "检查登录状态，然后明确刷新所选代码仓库。",
} satisfies MessageCatalog;
export default messages;
