import { useEffect, useState } from "react";
import type { GitHubAuthStatus, GitHubSnapshot, GitWorkspaceSnapshot } from "../../../shared/contracts";
import { filterIssues, filterRuns, runCategory, type RunFilter } from "../command/githubViewModel";
import { useI18n } from "../i18n";

export function GitHubPanel({ agentId, onError }: { agentId: string | null; onError(message: string): void }) {
  const { t } = useI18n();
  const [auth, setAuth] = useState<GitHubAuthStatus | null>(null); const [snapshot, setSnapshot] = useState<GitHubSnapshot | null>(null); const [busy, setBusy] = useState(false);
  const [local, setLocal] = useState<GitWorkspaceSnapshot | null>(null);
  const [label, setLabel] = useState(""); const [runFilter, setRunFilter] = useState<RunFilter>("");
  useEffect(() => { setSnapshot(null); setLocal(null); setAuth(null); setLabel(""); setRunFilter(""); }, [agentId]);
  async function refreshLocal() { if (!agentId) return; setBusy(true); try { setLocal(await window.orbi.git.snapshot({ agentId })); onError(""); } catch (error) { onError(message(error)); } finally { setBusy(false); } }
  async function checkAuth() { setBusy(true); try { setAuth(await window.orbi.github.authStatus()); onError(""); } catch (error) { onError(message(error)); } finally { setBusy(false); } }
  async function refresh() { if (!agentId) return; setBusy(true); try { const next = await window.orbi.github.snapshot({ agentId }); setSnapshot(next); setLabel((current) => current && !next.issues.some((issue) => issue.labels.includes(current)) ? "" : current); setAuth({ installed: true, authenticated: true }); onError(""); } catch (error) { onError(message(error)); } finally { setBusy(false); } }
  const issues = snapshot ? filterIssues(snapshot.issues, label) : [];
  const runs = snapshot ? filterRuns(snapshot.runs, runFilter) : [];
  const labels = snapshot ? [...new Set(snapshot.issues.flatMap((issue) => issue.labels))].sort() : [];
  if (!agentId) return <section className="command-panel"><div className="section-title">GitHub</div><p className="empty">{t("selectAgentRepository")}</p></section>;
  const activeRuns = snapshot?.runs.filter((run) => runCategory(run) === "active").length ?? 0; const attentionRuns = snapshot?.runs.filter((run) => runCategory(run) === "attention").length ?? 0;
  return <section className="command-panel github-panel" aria-label={t("githubIngestion")}>
    <div className="section-title"><span>{t("repositoryOperations")}</span><span className="mission-actions"><button type="button" disabled={busy} onClick={() => void refreshLocal()}>{t("inspectLocalGit")}</button><button type="button" disabled={busy} onClick={() => void checkAuth()}>{t("checkGithubAuth")}</button><button type="button" disabled={busy} onClick={() => void refresh()}>{t("refreshGithub")}</button></span></div>
    <p className="mission-policy">{t("localGitPolicy")}</p>
    {local ? <div className="git-local"><h3>{local.branch}</h3><small>{local.upstream ?? t("noUpstream")} · {t("ahead")} {local.ahead} · {t("behind")} {local.behind} · {local.changes.length} {t("changesCount")}</small><div className="github-grid"><div><h4>{t("workingChanges")}</h4>{local.changes.length ? <ul>{local.changes.map((change) => <li key={`${change.status}-${change.path}`}><strong>{change.status}</strong><span>{change.path}</span></li>)}</ul> : <p className="empty">{t("cleanTree")}</p>}</div><div><h4>{t("commitGraph")}</h4>{local.commits.length ? <ul>{local.commits.map((commit) => <li key={commit.hash}><strong>{commit.parentHashes.length > 1 ? "◆" : "●"} {commit.subject}</strong><small>{commit.hash} ← {commit.parentHashes.join(", ") || t("rootCommit")} · {new Date(commit.timestamp).toLocaleString()}</small></li>)}</ul> : <p className="empty">{t("noCommits")}</p>}</div></div>{local.diffStat ? <pre>{local.diffStat}</pre> : null}{local.diff ? <details><summary>{t("workingTreeDiff")}</summary><pre>{local.diff}</pre></details> : null}{local.truncated ? <small>{t("changesTruncated")}</small> : null}</div> : <p className="empty">{t("inspectGitPrompt")}</p>}
    <p className="mission-policy">{t("githubPolicy")}</p>
    {auth ? <p>{auth.installed ? auth.authenticated ? t("githubAuthenticated") : t("githubUnauthenticated") : t("githubMissing")}</p> : null}
    {snapshot ? <><h3>{snapshot.repository.nameWithOwner}</h3><small>{t("fetched")} {new Date(snapshot.fetchedAt).toLocaleString()} · {t("boundedGithub")}</small><p className="empty" aria-live="polite">{snapshot.issues.length} {t("openIssuesCount")} · {snapshot.runs.length} {t("recentRunsCount")} · {activeRuns} {t("activeRunsCount")} · {attentionRuns} {t("attentionRunsCount")} · {t("showing")} {issues.length} {t("issuesCount")} · {runs.length} {t("runsCount")}</p><div className="github-filters"><select aria-label={t("filterIssues")} value={label} onChange={(event) => setLabel(event.target.value)}><option value="">{t("allLabels")}</option>{labels.map((value) => <option key={value} value={value}>{value}</option>)}</select><select aria-label={t("filterRuns")} value={runFilter} onChange={(event) => setRunFilter(event.target.value as RunFilter)}><option value="">{t("allRuns")}</option><option value="active">{t("active")}</option><option value="success">{t("successful")}</option><option value="attention">{t("nonSuccess")}</option></select></div><div className="github-grid"><div><h4>{t("openIssues")}</h4>{issues.length ? <ul>{issues.map((issue) => <li key={issue.number}><strong>#{issue.number} · {issue.title}</strong><small>{issue.state} · {new Date(issue.updatedAt).toLocaleString()}</small><span>{issue.labels.join(", ") || t("noLabels")}</span></li>)}</ul> : <p className="empty">{t("noMatchingIssues")}</p>}</div><div><h4>{t("recentActionRuns")}</h4>{runs.length ? <ul>{runs.map((run) => <li key={run.id}><strong>{run.workflowName || run.name}</strong><small>{run.status} · {run.conclusion || t("pending")}</small><span>{run.headBranch} · {run.event} · {new Date(run.updatedAt).toLocaleString()}</span></li>)}</ul> : <p className="empty">{t("noMatchingRuns")}</p>}</div></div></> : <p className="empty">{t("githubRefreshPrompt")}</p>}
  </section>;
}
function message(error: unknown): string { return error instanceof Error ? error.message : String(error); }
