import { useEffect, useState } from "react";
import type { LocalModelEndpoint } from "../../../shared/contracts";

export function LocalModelPanel({ onError }: { onError(message: string): void }) {
  const [endpoints, setEndpoints] = useState<LocalModelEndpoint[]>([]); const [id, setId] = useState(""); const [name, setName] = useState("");
  const [baseUrl, setBaseUrl] = useState("http://127.0.0.1:11434/v1"); const [defaultModel, setDefaultModel] = useState(""); const [busy, setBusy] = useState(false); const [probe, setProbe] = useState<Record<string, string>>({});
  async function refresh() { try { setEndpoints(await window.orbi.localModels.list()); } catch (error) { onError(message(error)); } }
  useEffect(() => { void refresh(); }, []);
  async function create(event: React.FormEvent) { event.preventDefault(); setBusy(true); try { setEndpoints(await window.orbi.localModels.create({ id, name, baseUrl, defaultModel: defaultModel || undefined })); setId(""); setName(""); setDefaultModel(""); onError(""); } catch (error) { onError(message(error)); } finally { setBusy(false); } }
  async function saveCredential(endpoint: LocalModelEndpoint) { setBusy(true); try { setEndpoints(await window.orbi.localModels.saveCredentialFromClipboard({ id: endpoint.id })); onError(""); } catch (error) { onError(message(error)); } finally { setBusy(false); } }
  async function clearCredential(endpoint: LocalModelEndpoint) { setBusy(true); try { setEndpoints(await window.orbi.localModels.clearCredential({ id: endpoint.id })); onError(""); } catch (error) { onError(message(error)); } finally { setBusy(false); } }
  async function remove(endpoint: LocalModelEndpoint) { setBusy(true); try { setEndpoints(await window.orbi.localModels.remove({ id: endpoint.id })); setProbe((current) => { const next = { ...current }; delete next[endpoint.id]; return next; }); onError(""); } catch (error) { onError(message(error)); } finally { setBusy(false); } }
  async function runProbe(endpoint: LocalModelEndpoint) { setBusy(true); try { const result = await window.orbi.localModels.probe({ id: endpoint.id }); setProbe((current) => ({ ...current, [endpoint.id]: result.models.length ? `${result.models.join(", ")}${result.truncated ? " …" : ""}` : "Connected; no models reported." })); onError(""); } catch (error) { onError(message(error)); } finally { setBusy(false); } }
  return <section className="command-panel local-model-panel" aria-label="Local OpenAI-compatible endpoints">
    <div className="section-title"><span>Local model endpoints</span><button type="button" onClick={() => void refresh()}>Refresh</button></div>
    <p className="mission-policy">Loopback OpenAI-compatible `/v1` endpoints only. To keep credentials out of renderer state, copy a key and use Save key from clipboard; the main process encrypts it with the operating system credential facility. Clear your clipboard afterward.</p>
    <form className="mission-create" onSubmit={create}><input aria-label="Endpoint identifier" value={id} onChange={(event) => setId(event.target.value)} placeholder="endpoint-id" pattern="[a-z0-9][a-z0-9-]{0,47}" maxLength={48} required /><input aria-label="Endpoint display name" value={name} onChange={(event) => setName(event.target.value)} placeholder="Display name" maxLength={80} required /><input aria-label="Endpoint base URL" type="url" value={baseUrl} onChange={(event) => setBaseUrl(event.target.value)} placeholder="http://127.0.0.1:11434/v1" required /><input aria-label="Default model" value={defaultModel} onChange={(event) => setDefaultModel(event.target.value)} placeholder="Default model (optional)" maxLength={200} /><button type="submit" disabled={busy}>Add local endpoint</button></form>
    {endpoints.length ? <ul>{endpoints.map((endpoint) => <li key={endpoint.id}><strong>{endpoint.name}</strong><small>{endpoint.baseUrl} · {endpoint.hasApiKey ? "encrypted key saved" : "no key"}{endpoint.defaultModel ? ` · ${endpoint.defaultModel}` : ""}</small>{probe[endpoint.id] ? <span>{probe[endpoint.id]}</span> : null}<span className="mission-actions"><button type="button" disabled={busy} onClick={() => void runProbe(endpoint)}>Probe models</button><button type="button" disabled={busy} onClick={() => void saveCredential(endpoint)}>Save key from clipboard</button>{endpoint.hasApiKey ? <button type="button" disabled={busy} onClick={() => void clearCredential(endpoint)}>Clear key</button> : null}<button type="button" disabled={busy} onClick={() => void remove(endpoint)}>Remove</button></span></li>)}</ul> : <p className="empty">No local model endpoints configured.</p>}
  </section>;
}
function message(error: unknown): string { return error instanceof Error ? error.message : String(error); }
