import { useState } from "react";
import type { RemoteCatalogReview } from "../../../shared/contracts";
import { useI18n } from "../i18n";
import { PixelButton } from "./ui/PixelButton";
import { PixelPanel } from "./ui/PixelPanel";
export function RemoteCatalogPanel({ onError }: { onError(message: string): void }) {
  const { t } = useI18n(); const [url, setUrl] = useState(""); const [publisherId, setPublisherId] = useState(""); const [keyId, setKeyId] = useState(""); const [publicKey, setPublicKey] = useState(""); const [review, setReview] = useState<RemoteCatalogReview | null>(null); const [loading, setLoading] = useState(false);
  async function submit() { setLoading(true); onError(""); try { setReview(await window.orbi.catalogs.review({ url, publisherId, keyId, publicKey })); } catch (error) { setReview(null); onError(error instanceof Error ? error.message : String(error)); } finally { setLoading(false); } }
  return <PixelPanel title={t("trustedCatalog")} eyebrow={t("reviewOnly")} ariaLabel={t("trustedCatalog")}><p className="skills-policy">{t("catalogPolicy")}</p><form className="skills-search" onSubmit={(event) => { event.preventDefault(); void submit(); }}><label>{t("catalogUrl")}<input aria-label={t("catalogUrl")} type="url" required maxLength={2048} value={url} onChange={(event) => setUrl(event.target.value)} placeholder="https://catalog.example/manifest.json" /></label><label>{t("publisherId")}<input aria-label={t("publisherId")} required maxLength={128} value={publisherId} onChange={(event) => setPublisherId(event.target.value)} /></label><label>{t("publisherKeyId")}<input aria-label={t("publisherKeyId")} required maxLength={128} value={keyId} onChange={(event) => setKeyId(event.target.value)} /></label><label>{t("publisherPublicKey")}<textarea aria-label={t("publisherPublicKey")} required maxLength={1000} value={publicKey} onChange={(event) => setPublicKey(event.target.value.trim())} /></label><PixelButton type="submit" variant="primary" disabled={loading}>{loading ? t("verifying") : t("verifyCatalog")}</PixelButton></form>{review ? <><p className="mission-policy">{review.publisherId} · {review.keyId} · {review.entries.length} {t("catalogEntries")} · {review.fromCache ? t("cached") : t("verified")}</p><ul className="skills-grid">{review.entries.map((entry) => <li key={entry.id}><strong>{entry.name}</strong><small>{entry.kind} · {entry.version} · {entry.size} B</small><span>{entry.description}</span></li>)}</ul></> : <p className="empty">{t("noCatalogReviewed")}</p>}</PixelPanel>;
}
