import assert from "node:assert/strict";
import { mkdtemp, readFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { SlackStore } from "../src/main/slack/slackStore";
const cipher = { isAvailable: () => true, encrypt: (value: string) => Buffer.from(`sealed:${value}`), decrypt: (value: Buffer) => value.toString().replace(/^sealed:/, "") };
test("Slack store encrypts bot and signing credentials and exposes only redacted status", async () => { const root = await mkdtemp(path.join(os.tmpdir(), "orbi-slack-")); const file = path.join(root, "slack.json"); const store = new SlackStore(file, cipher, () => 123); await store.load(); assert.deepEqual(await store.setToken("xoxb-1234567890-abcdefghij"), { configured: true, signingConfigured: false, updatedAt: 123 }); assert.deepEqual(await store.setSigningSecret("0123456789abcdef0123456789abcdef"), { configured: true, signingConfigured: true, updatedAt: 123 }); const stored = await readFile(file, "utf8"); assert.equal(stored.includes("xoxb-"), false); assert.equal(stored.includes("0123456789abcdef"), false); assert.equal(store.token(), "xoxb-1234567890-abcdefghij"); assert.equal(store.signingSecret(), "0123456789abcdef0123456789abcdef"); assert.equal((await store.clear()).configured, false); });
test("Slack store fails closed without secure storage or a bot token", async () => { const root = await mkdtemp(path.join(os.tmpdir(), "orbi-slack-")); const store = new SlackStore(path.join(root, "slack.json"), { ...cipher, isAvailable: () => false }); await store.load(); await assert.rejects(store.setToken("xoxb-1234567890-abcdefghij"), /unavailable/); await assert.rejects(store.setToken("xoxp-user-token"), /bot token/); assert.throws(() => store.token(), /not configured/); });
