import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";
export type Locale = "en" | "zh-CN" | "ar";
const messages = {
  en: {
    locale: "Interface language", help: "OrbiAgents uses only the language selected here and never reads the operating-system locale.", subtitle: "Local command deck · authenticated runtime telemetry", active: "active", hire: "Hire agent",
    commandCenter: "Command Center", operate: "Operate", coordinate: "Coordinate", observe: "Observe", system: "System",
    floor: "Floor", terminals: "Terminals", files: "Files", repository: "Repository", tasks: "Tasks", messages: "Messages", approvals: "Approvals", memory: "Memory", skills: "Skills", activity: "Activity", costs: "Costs", recovery: "Recovery", workspaces: "Workspaces", settings: "Settings", updates: "Updates", setup: "Setup",
    hireTitle: "Hire orbital agent", fleetConfiguration: "Fleet configuration", configureSpecialist: "Configure a specialist", profileRetention: "Profiles are validated and retained with the local agent session.", importHire: "Import hire", copyHire: "Copy hire", close: "Close", localGallery: "Local agent gallery", role: "Role",
    generalist: "Generalist", generalistDetail: "Balanced execution", planner: "Planner", plannerDetail: "Break down missions", builder: "Builder", builderDetail: "Implement changes", reviewer: "Reviewer", reviewerDetail: "Audit and verify", researcher: "Researcher", researcherDetail: "Investigate evidence",
    callSign: "Call sign", agentName: "Agent name", runtime: "Runtime", agentRuntime: "Agent runtime", workspace: "Workspace", workspacePath: "Agent workspace path", workspacePlaceholder: "/absolute/path/to/project", timebox: "Timebox", planningTimebox: "Agent planning timebox", minutes30: "30 minutes", hour1: "1 hour", hours2: "2 hours", hours4: "4 hours", missionGoal: "Mission goal", missionGoalLabel: "Agent mission goal", missionGoalPlaceholder: "Describe the outcome this agent owns",
    capabilities: "Capabilities", planning: "planning", coding: "coding", review: "review", research: "research", testing: "testing", signalColor: "Signal color", cyan: "cyan", violet: "violet", green: "green", gold: "gold", rose: "rose", isolatedWorktree: "Isolated worktree", useIsolatedWorktree: "Use isolated worktree", launching: "Launching…", launchAgent: "Launch agent", roleSuffix: "role", capabilitySuffix: "capability", colorSuffix: "signal color",
    hireLinkImported: "Hire link imported. Review it and choose a workspace before launching.", hireLinkCopied: "Hire link copied. Workspace paths and credentials are never included.", profileImported: "Profile imported. Review it and choose a workspace before launching.", profileSelected: "profile selected. Review before launching.",
  },
  "zh-CN": {
    locale: "界面语言", help: "OrbiAgents 仅使用此处选择的语言，不读取操作系统语言。", subtitle: "本地智能体指挥台 · 已验证的运行遥测", active: "运行中", hire: "聘用智能体",
    commandCenter: "指挥中心", operate: "操作", coordinate: "协作", observe: "监控", system: "系统",
    floor: "总览", terminals: "终端", files: "文件", repository: "代码仓库", tasks: "任务", messages: "消息", approvals: "审批", memory: "记忆", skills: "技能", activity: "活动", costs: "成本", recovery: "恢复", workspaces: "工作区", settings: "设置", updates: "更新", setup: "配置",
    hireTitle: "聘用轨道智能体", fleetConfiguration: "团队配置", configureSpecialist: "配置专用智能体", profileRetention: "配置会经过验证并保存在本地智能体会话中。", importHire: "导入聘用配置", copyHire: "复制聘用配置", close: "关闭", localGallery: "本地智能体模板", role: "角色",
    generalist: "通用型", generalistDetail: "均衡执行", planner: "规划者", plannerDetail: "拆解任务", builder: "构建者", builderDetail: "实现变更", reviewer: "审查者", reviewerDetail: "审计并验证", researcher: "研究者", researcherDetail: "调查证据",
    callSign: "代号", agentName: "智能体名称", runtime: "运行时", agentRuntime: "智能体运行时", workspace: "工作区", workspacePath: "智能体工作区路径", workspacePlaceholder: "/项目的/绝对路径", timebox: "时间限制", planningTimebox: "智能体规划时间限制", minutes30: "30 分钟", hour1: "1 小时", hours2: "2 小时", hours4: "4 小时", missionGoal: "任务目标", missionGoalLabel: "智能体任务目标", missionGoalPlaceholder: "描述此智能体负责的成果",
    capabilities: "能力", planning: "规划", coding: "编码", review: "审查", research: "研究", testing: "测试", signalColor: "标识颜色", cyan: "青色", violet: "紫色", green: "绿色", gold: "金色", rose: "玫红", isolatedWorktree: "隔离工作树", useIsolatedWorktree: "使用隔离工作树", launching: "正在启动…", launchAgent: "启动智能体", roleSuffix: "角色", capabilitySuffix: "能力", colorSuffix: "标识颜色",
    hireLinkImported: "聘用链接已导入。请检查并在启动前选择工作区。", hireLinkCopied: "聘用链接已复制，其中不会包含工作区路径或凭据。", profileImported: "配置已导入。请检查并在启动前选择工作区。", profileSelected: "配置已选择，请在启动前检查。",
  },
  ar: {
    locale: "لغة الواجهة", help: "يستخدم OrbiAgents اللغة المحددة هنا فقط ولا يقرأ لغة نظام التشغيل.", subtitle: "مركز قيادة محلي · قياس تشغيل موثّق", active: "نشط", hire: "توظيف وكيل",
    commandCenter: "مركز القيادة", operate: "تشغيل", coordinate: "تنسيق", observe: "مراقبة", system: "النظام",
    floor: "الساحة", terminals: "الطرفيات", files: "الملفات", repository: "المستودع", tasks: "المهام", messages: "الرسائل", approvals: "الموافقات", memory: "الذاكرة", skills: "المهارات", activity: "النشاط", costs: "التكاليف", recovery: "الاستعادة", workspaces: "مساحات العمل", settings: "الإعدادات", updates: "التحديثات", setup: "التهيئة",
    hireTitle: "توظيف وكيل مداري", fleetConfiguration: "إعداد الأسطول", configureSpecialist: "إعداد وكيل متخصص", profileRetention: "يتم التحقق من الملفات وحفظها مع جلسة الوكيل المحلية.", importHire: "استيراد التوظيف", copyHire: "نسخ التوظيف", close: "إغلاق", localGallery: "معرض الوكلاء المحلي", role: "الدور",
    generalist: "عام", generalistDetail: "تنفيذ متوازن", planner: "مخطط", plannerDetail: "تقسيم المهام", builder: "منفذ", builderDetail: "تنفيذ التغييرات", reviewer: "مراجع", reviewerDetail: "تدقيق وتحقق", researcher: "باحث", researcherDetail: "فحص الأدلة",
    callSign: "الاسم الرمزي", agentName: "اسم الوكيل", runtime: "بيئة التشغيل", agentRuntime: "بيئة تشغيل الوكيل", workspace: "مساحة العمل", workspacePath: "مسار مساحة عمل الوكيل", workspacePlaceholder: "/المسار/المطلق/للمشروع", timebox: "المدة", planningTimebox: "مدة تخطيط الوكيل", minutes30: "30 دقيقة", hour1: "ساعة واحدة", hours2: "ساعتان", hours4: "4 ساعات", missionGoal: "هدف المهمة", missionGoalLabel: "هدف مهمة الوكيل", missionGoalPlaceholder: "صف النتيجة التي يمتلكها هذا الوكيل",
    capabilities: "القدرات", planning: "تخطيط", coding: "برمجة", review: "مراجعة", research: "بحث", testing: "اختبار", signalColor: "لون الإشارة", cyan: "سماوي", violet: "بنفسجي", green: "أخضر", gold: "ذهبي", rose: "وردي", isolatedWorktree: "شجرة عمل معزولة", useIsolatedWorktree: "استخدام شجرة عمل معزولة", launching: "جارٍ التشغيل…", launchAgent: "تشغيل الوكيل", roleSuffix: "دور", capabilitySuffix: "قدرة", colorSuffix: "لون إشارة",
    hireLinkImported: "تم استيراد رابط التوظيف. راجعه واختر مساحة عمل قبل التشغيل.", hireLinkCopied: "تم نسخ رابط التوظيف. لا يتم تضمين مسارات العمل أو بيانات الاعتماد.", profileImported: "تم استيراد الملف. راجعه واختر مساحة عمل قبل التشغيل.", profileSelected: "تم اختيار الملف. راجعه قبل التشغيل.",
  },
} as const;
export type MessageKey = keyof typeof messages.en;
const Context = createContext<{ locale: Locale; setLocale(locale: Locale): void; t(key: MessageKey): string }>({ locale: "en", setLocale: () => undefined, t: (key) => messages.en[key] });
export function I18nProvider({ children }: { children: ReactNode }) { const [locale, setLocale] = useState<Locale>(() => { try { const saved = localStorage.getItem("orbiagents.locale"); return saved === "zh-CN" || saved === "ar" ? saved : "en"; } catch { return "en"; } }); useEffect(() => { document.documentElement.lang = locale; document.documentElement.dir = locale === "ar" ? "rtl" : "ltr"; try { localStorage.setItem("orbiagents.locale", locale); } catch { /* optional */ } }, [locale]); const value = useMemo(() => ({ locale, setLocale, t: (key: MessageKey) => messages[locale][key] }), [locale]); return <Context.Provider value={value}>{children}</Context.Provider>; }
export function useI18n() { return useContext(Context); }
