import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";
export type Locale = "en" | "zh-CN" | "ar";
const englishMessages = {
    locale: "Interface language", help: "OrbiAgents uses only the language selected here and never reads the operating-system locale.", subtitle: "Local command deck · authenticated runtime telemetry", active: "active", hire: "Hire agent",
    commandCenter: "Command Center", operate: "Operate", coordinate: "Coordinate", observe: "Observe", system: "System", general: "General", orbitalAgentOperations: "ORBITAL AGENT OPERATIONS",
    orbitalFloorTitle: "Orbital floor", orbitalFloorDescription: "Watch the live fleet and move between operational floors.", agentTerminals: "Agent terminals", agentTerminalsDescription: "Steer a selected agent through its real terminal session.", workspaceIdeDescription: "Inspect and safely edit the selected agent workspace.", repositoryIntelligence: "Repository intelligence", repositoryDescription: "Inspect local Git changes, history, GitHub issues, and CI through bounded read-only access.", missionBoard: "Mission board", missionBoardDescription: "Assign dependency-aware durable work through Orbi-Prime.", fleetMessages: "Fleet messages", fleetMessagesDescription: "Inspect durable agent-to-agent delivery and replies.", operatorApprovalsDescription: "Review spend, destructive-operation, and scope-expansion gates.", projectMemoryDescription: "Capture and retrieve bounded project knowledge.", skillsCatalog: "Skills catalog", skillsCatalogDescription: "Search installed agent capabilities without executing their instructions.", liveActivity: "Live activity", liveActivityDescription: "Filter verified runtime signals across the active fleet.", costLedger: "Cost ledger", costLedgerDescription: "Audit durable authorization estimates and integrity status.", recoveryCenter: "Recovery center", recoveryCenterDescription: "Inspect interrupted work without automatically restarting it.", workspaceRegistry: "Workspace registry", workspaceRegistryDescription: "Find direct, isolated, and preserved agent workspaces.", fleetSettings: "Fleet settings", fleetSettingsDescription: "Configure runtimes, local models, and scheduled missions.", applicationUpdatesDescription: "Check, download, and explicitly install signed OrbiAgents releases.", systemSetup: "System setup", systemSetupDescription: "Re-run read-only prerequisite and platform checks.", noAgentSelected: "No agent selected", selectedAgentDetails: "Selected agent details", terminal: "Terminal", stop: "Stop", loadingPixelOffice: "Loading pixel office", loadingTerminal: "Loading terminal", loadingWorkspaceEditor: "Loading workspace editor", noDurableMessages: "No durable messages for this project.", agentWorkspaces: "Agent workspaces", noAgentWorkspaces: "No agent workspaces recorded.", direct: "direct",
    floor: "Floor", terminals: "Terminals", files: "Files", repository: "Repository", tasks: "Tasks", messages: "Messages", approvals: "Approvals", memory: "Memory", skills: "Skills", activity: "Activity", costs: "Costs", recovery: "Recovery", workspaces: "Workspaces", settings: "Settings", updates: "Updates", setup: "Setup",
    hireTitle: "Hire orbital agent", fleetConfiguration: "Fleet configuration", configureSpecialist: "Configure a specialist", profileRetention: "Profiles are validated and retained with the local agent session.", importHire: "Import hire", copyHire: "Copy hire", close: "Close", localGallery: "Local agent gallery", role: "Role",
    generalist: "Generalist", generalistDetail: "Balanced execution", planner: "Planner", plannerDetail: "Break down missions", builder: "Builder", builderDetail: "Implement changes", reviewer: "Reviewer", reviewerDetail: "Audit and verify", researcher: "Researcher", researcherDetail: "Investigate evidence",
    callSign: "Call sign", agentName: "Agent name", runtime: "Runtime", agentRuntime: "Agent runtime", workspace: "Workspace", workspacePath: "Agent workspace path", workspacePlaceholder: "/absolute/path/to/project", timebox: "Timebox", planningTimebox: "Agent planning timebox", minutes30: "30 minutes", hour1: "1 hour", hours2: "2 hours", hours4: "4 hours", missionGoal: "Mission goal", missionGoalLabel: "Agent mission goal", missionGoalPlaceholder: "Describe the outcome this agent owns",
    capabilities: "Capabilities", planning: "planning", coding: "coding", review: "review", research: "research", testing: "testing", signalColor: "Signal color", cyan: "cyan", violet: "violet", green: "green", gold: "gold", rose: "rose", isolatedWorktree: "Isolated worktree", useIsolatedWorktree: "Use isolated worktree", launching: "Launching…", launchAgent: "Launch agent", roleSuffix: "role", capabilitySuffix: "capability", colorSuffix: "signal color",
    hireLinkImported: "Hire link imported. Review it and choose a workspace before launching.", hireLinkCopied: "Hire link copied. Workspace paths and credentials are never included.", profileImported: "Profile imported. Review it and choose a workspace before launching.", profileSelected: "profile selected. Review before launching.",
    commandComposer: "Agent command composer", command: "Command", agentCommand: "Agent command", sendInstruction: "Send an instruction to", selectRunningAgent: "Select a running agent", queue: "Queue", workspaceAttachment: "Workspace file attachment", attachWorkspaceFile: "Attach workspace file…", attach: "Attach", remove: "Remove", queuedEncrypted: "queued · encrypted local resume", sending: "Sending…", sendAll: "Send all", filesCount: "files", retry: "Retry", send: "Send",
    agentRoster: "Agent roster", agentFleet: "Agent fleet", registered: "registered", emptyFleet: "Launch your first agent to populate the command deck.", workspaceSuffix: "workspace", agentActivity: "Agent activity", signalLog: "Signal log", liveTelemetry: "live telemetry", emptySignals: "Runtime signals will appear here.",
    selectAgentRepository: "Select an agent to inspect its workspace repository.", githubIngestion: "GitHub issue and CI ingestion", repositoryOperations: "Repository operations", inspectLocalGit: "Inspect local Git", checkGithubAuth: "Check GitHub auth", refreshGithub: "Refresh GitHub", localGitPolicy: "Local Git inspection is read-only and bounded. It never stages, commits, switches branches, or pushes.", noUpstream: "No upstream", ahead: "ahead", behind: "behind", changesCount: "changes", workingChanges: "Working changes", cleanTree: "Working tree is clean.", recentCommits: "Recent commits", noCommits: "No commits loaded.", changesTruncated: "Working changes are truncated to 200 entries.", inspectGitPrompt: "Inspect local Git to load branch, change, and commit facts.", githubPolicy: "Read-only and operator-triggered. Uses the locally authenticated gh CLI without token IPC, login automation, polling, or workflow mutation.", githubAuthenticated: "GitHub CLI is locally authenticated.", githubUnauthenticated: "GitHub CLI is not authenticated. Run gh auth login in your terminal.", githubMissing: "GitHub CLI is not installed.", fetched: "Fetched", boundedGithub: "bounded to 50 issues and 30 runs", openIssuesCount: "open issues", recentRunsCount: "recent runs", activeRunsCount: "active", attentionRunsCount: "non-success completed", showing: "showing", issuesCount: "issues", runsCount: "runs", filterIssues: "Filter issues by label", allLabels: "All loaded labels", filterRuns: "Filter workflow runs", allRuns: "All recent runs", successful: "Successful", nonSuccess: "Non-success completed", openIssues: "Open issues", noLabels: "No labels", noMatchingIssues: "No loaded issues match this label.", recentActionRuns: "Recent Actions runs", pending: "pending", noMatchingRuns: "No loaded runs match this state.", githubRefreshPrompt: "Check authentication, then explicitly refresh the selected repository.",
    welcome: "Welcome to OrbiAgents", setupPrerequisites: "Setup and prerequisites", systemReadiness: "system readiness", orbiSetup: "OrbiAgents setup", rerunChecks: "Run checks again", setupPolicy: "These checks inspect executable access and platform capabilities only. OrbiAgents will not install software, change PATH, authenticate accounts, or block access to the Command Center.", prerequisitesReady: "Core prerequisites are ready.", prerequisitesMissing: "Some core prerequisites are missing.", required: "required", optional: "optional", continueOrbi: "Continue to OrbiAgents", continueMissing: "Continue without missing tools", lastChecked: "Last checked", onboardingAcknowledged: "onboarding acknowledged",
    startupRecovery: "Startup recovery", readOnlyInventory: "read-only inventory", recoveryReport: "Startup recovery report", refreshReport: "Refresh report", recoveryPolicy: "Read-only inventory. Recovery never restarts commands, delivers tasks, changes worktrees, or decides approvals.", loadingRecovery: "Loading recovery report…", needReview: "need review.", reportTruncated: "The bounded report was truncated.", noRecoveryItems: "No interrupted sessions or unfinished durable work were detected.", inventoryGenerated: "Inventory generated",
    orbiHive: "Orbi Hive", selectHive: "Select or launch an agent to open its project Hive.", hiveOperatorPanel: "Orbi Hive operator panel", refresh: "Refresh", approvalReason: "Approval reason", rejectionReason: "Rejection reason", completedResult: "Completed task result", taskTitle: "Task title", taskForPrime: "Task for Orbi-Prime", taskDetails: "Task details", assignedAgent: "Assigned project agent", selectProjectAgent: "Select project agent", assignPrime: "Assign through Orbi-Prime", approvalsTitle: "Approvals", approve: "Approve", reject: "Reject", noApprovals: "No approvals.", primeInbox: "Prime inbox", noMessages: "No messages.", blackboard: "Blackboard", noSharedResults: "No shared results.", taskOperations: "Task operations", total: "total", actionable: "actionable", blockedCount: "blocked", waitingDependencies: "waiting on dependencies", completedCount: "completed", failedCount: "failed", retriedCount: "retried", noTasksAssigned: "No tasks assigned yet", queuedColumn: "Queued", activeColumn: "Active", blockedColumn: "Blocked", doneColumn: "Done", tasksSuffix: "tasks", unassigned: "unassigned", attempt: "attempt", start: "Start", block: "Block", complete: "Complete", noTasks: "No tasks", healthFailed: "Failed — review required", healthBlocked: "Blocked — operator action required", healthWaiting: "Waiting on dependencies", healthRetry: "Retry", healthCompleted: "Completed", healthRunning: "Running", healthReady: "Ready", noDependencies: "No dependencies", dependenciesUnresolved: "dependencies unresolved", dependenciesComplete: "dependencies complete", of: "of",
    applicationUpdates: "Application updates", installed: "installed", loading: "loading", orbiUpdates: "OrbiAgents updates", updatePolicy: "Updates are operator-controlled. OrbiAgents never checks, downloads, or restarts silently, and restart fails closed while agents, approvals, missions, or preserved workspaces require attention.", version: "Version", checking: "Checking…", checkUpdates: "Check for updates", downloading: "Downloading…", download: "Download", restartInstall: "Restart and install", updateReading: "Reading update status…", updateReadyCheck: "Ready to check", updateCheckingReleases: "Checking GitHub releases…", updateAvailable: "Update available", updateCurrent: "You are up to date", updateDownloadingPackage: "Downloading release package…", updateReadyInstall: "Update ready to install", updateFailed: "Update action failed",
    operatorApprovals: "Operator approvals", noProjectApprovals: "No approval requests for this project.", applyWorkspaceConfirm: "Apply the selected files to the clean source repository?", discardWorkspaceConfirm: "Permanently discard this preserved worktree and all of its unmerged changes?", preservedChanges: "Preserved workspace changes", changesPreserved: "Changes preserved for review", recoveryDetailsMissing: "Recovered after restart. Change details could not be refreshed automatically.", applyTrackedFile: "Apply tracked file", applyNewFile: "Apply new file", tracked: "tracked", newFile: "new", applySelected: "Apply selected", discardWorktree: "Discard worktree",
    installedSkills: "Installed skills", discovered: "discovered", installedAgentSkills: "Installed agent skills", searchSkills: "Search skills", searchInstalledSkills: "Search installed skills", skillsPlaceholder: "Testing, Android, security…", source: "Source", filterSkillsSource: "Filter skills by source", allSources: "All sources", scanning: "Scanning…", search: "Search", reset: "Reset", skillsPolicy: "Browsing reads bounded frontmatter and never executes skill instructions. Removal requires confirmation and moves only a freshly verified installed skill directory to the OS Trash.", moveTrash: "Move to Trash", scanningSkills: "Scanning installed skills…", noSkillsMatch: "No installed skills match this search.", removeSkillPrefix: "Move the installed skill", removeSkillSuffix: "to Trash?",
    projectMemory: "Project memory", selectProjectMemory: "Select an agent to open its project memory.", markdownMemory: "Project markdown memory", memoryTitle: "Memory title", memoryContent: "Memory content", memoryContentPlaceholder: "Verified decision, result, or reusable context", capture: "Capture", searchProjectMemory: "Search project memory", searchLocalMemory: "Search local memory", clear: "Clear", noMemoryResults: "No results for", noProjectMemories: "No project memories captured yet", resultsFor: "results for", projectMemories: "project memories", sourcesCount: "sources", condensed: "condensed", knowledgeMap: "Knowledge map", verifiedRelationships: "verified text relationships", sharedConcepts: "Shared concepts", noRelationships: "Capture related project memories to reveal deterministic connections.",
    normalizedActivity: "Normalized runtime activity", clearFilters: "Clear filters", noSessionSignals: "No runtime signals in this desktop session", signals: "signals", agentsCount: "agents", providerEvents: "provider events", needAttention: "need attention", filterActivityAgent: "Filter activity by agent", allAgents: "All agents", filterActivitySource: "Filter activity by source", filterActivityState: "Filter activity by state", allStates: "All states", noSignalMatches: "No signals match these filters.",
    usageCosts: "Usage and cost controls", measuredTelemetry: "measured session telemetry", refreshLedger: "Refresh ledger", providerSignals: "provider signals", agentMinutes: "agent-minutes", allSignals: "all signals", telemetryPolicy: "Session telemetry counts sanitized runtime signals and elapsed agent time. Providers do not expose consistent token or tool totals here, so OrbiAgents does not fabricate them.", observedWork: "Observed work", noProviderActivity: "No provider activity has been measured in this desktop session.", estimatePolicy: "Local operator-authorized estimates only. These values are not token measurements, provider invoices, or actual charges.", ledgerCorrupt: "Ledger integrity is uncertain. The verified prefix is shown and new cost entries are blocked.", ledgerEstimate: "ledger-wide authorized estimate across every verified entry.", noCostAuthorizations: "No verified cost authorizations", verifiedEntries: "verified entries", projectsCount: "projects", visibleEstimate: "visible estimate", boundedSet: "newest bounded set", project: "Project", filterCostsProject: "Filter costs by project", allLoadedProjects: "All loaded projects", approvedEstimate: "operator-approved estimate", mission: "Mission", run: "run", noCostMatches: "No loaded entries match this project.", costTruncated: "Showing only the newest 200 verified entries; the ledger-wide total above includes the complete verified chain.", loadingLedger: "Loading cost ledger…",
    inboundWebhooks: "Inbound webhooks", webhookPolicy: "Disabled by default and bound only to loopback. Each launch creates a new secret; callers must send Bearer authentication and a unique X-Orbi-Event-Id. Secrets are copied directly to the clipboard and never exposed to the renderer.", loopbackEndpoint: "Loopback endpoint", copyWebhookSecret: "Copy webhook secret", secretCopied: "Secret copied", recentWebhookEvents: "Recent webhook events", noWebhookEvents: "No webhook events received.",
    runtimeAdapters: "Runtime adapters", adapterPolicy: "Custom adapters are explicit local allowlist entries. Executables must use absolute paths; arguments are passed literally without a shell. Secrets and environment overrides are not supported.", adapterId: "Adapter identifier", adapterName: "Adapter display name", displayName: "Display name", adapterPath: "Adapter executable path", executablePlaceholder: "/absolute/path/to/executable", adapterArguments: "Adapter arguments, one per line", argumentsPlaceholder: "One literal argument per line (optional)", addAdapter: "Add allowlisted adapter", builtIn: "built-in", customAllowlisted: "custom allowlisted",
    localEndpointsLabel: "Local OpenAI-compatible endpoints", localEndpoints: "Local model endpoints", localEndpointPolicy: "Loopback OpenAI-compatible /v1 endpoints only. To keep credentials out of renderer state, copy a key and use Save key from clipboard; the main process encrypts it with the operating system credential facility. Clear your clipboard afterward.", endpointId: "Endpoint identifier", endpointName: "Endpoint display name", endpointUrl: "Endpoint base URL", defaultModel: "Default model", optionalDefaultModel: "Default model (optional)", addEndpoint: "Add local endpoint", encryptedKey: "encrypted key saved", noKey: "no key", probeModels: "Probe models", saveClipboardKey: "Save key from clipboard", clearKey: "Clear key", noEndpoints: "No local model endpoints configured.", connectedNoModels: "Connected; no models reported.",
    scheduledMissions: "Scheduled missions", selectMissions: "Select an agent to manage its project missions.", missionsHeartbeat: "Scheduled missions and heartbeat", missionPolicy: "Disabled by default. Heartbeat only requests a run-bound spend approval; execution still requires approval and an explicit Run action.", noScheduledMissions: "No scheduled missions", missionsCount: "missions", enabledCount: "enabled", pendingRuns: "pending runs", enabledRunEstimate: "enabled-run estimate", missionTitle: "Mission title", missionInstructions: "Mission instructions", missionAgent: "Mission agent", everyMinutes: "Every minutes", missionInterval: "Mission interval in minutes", estimatedUsd: "Estimated USD", missionEstimate: "Mission estimated cost in USD", createDisabled: "Create disabled", every: "every", enabled: "enabled", disabled: "disabled", nextDue: "Next due", lastRun: "last run", disable: "Disable", enable: "Enable", runApproved: "Run if approved", missionDisabledStatus: "Disabled — no heartbeat runs", taskDispatchPending: "Task dispatch pending", approvalExecutionGated: "Approval requested — execution remains gated", preparingApproval: "Preparing approval request", waitingHeartbeat: "Enabled — waiting for next heartbeat",
    workspaceFiles: "Workspace files", selectWorkspace: "Select an agent to open its recorded workspace.", workspaceEditor: "Workspace file editor", workspaceIde: "Workspace IDE", changes: "Changes", history: "History", railSuffix: "rail", largeFile: "large", noFileHistory: "No file history.", compareRevision: "Compare with Git revision", workingCopy: "Working copy", exitCompare: "Exit compare", save: "Save", historicalRevision: "Historical file revision", currentFileContent: "Current file content", editorFor: "Editor for", chooseEditable: "Choose an editable text file. Secret-bearing, binary, symlinked, and oversized files are excluded.", discardEditorChanges: "Discard unsaved editor changes?", saveChangesTo: "Save changes to", changedFileUnavailable: "Changed file is unavailable in the safe editable file tree",
    pixelOffice: "OrbiAgents pixel office", liveOrbitalDeck: "LIVE ORBITAL DECK", floorSuffix: "Floor", officeControls: "Office floor and camera controls", orbitalFloor: "Orbital office floor", operationsFloor: "Operations", engineeringFloor: "Engineering", supportFloor: "Support", locateAgentOn: "Locate selected agent on", panLeft: "Pan office left", panUp: "Pan office up", panDown: "Pan office down", panRight: "Pan office right", setZoom: "Set office zoom to", pendingApprovals: "pending approvals", noHiveSelected: "No project Hive selected", accessibleAgentControls: "Accessible office agent controls", commandBridge: "Command Bridge", codeForge: "Code Forge", signalBay: "Signal Bay", researchLab: "Research Lab", reviewDeck: "Review Deck", orbiPrime: "Orbi-Prime", stateIdle: "idle", stateThinking: "thinking", stateReading: "reading", stateCoding: "coding", statePermissionWaiting: "permission waiting", stateDone: "done", stateFailed: "failed", bubbleStandby: "STANDBY", bubblePlan: "PLAN", bubbleRead: "READ", bubbleCode: "CODE", bubbleApprove: "APPROVE?", bubbleDone: "DONE", bubbleError: "ERROR", zonePlanning: "planning", zoneFocus: "focus", zoneCollaboration: "collaboration", zoneLounge: "lounge",
    voiceControl: "Voice control", consentRetention: "consent and retention", voicePolicy: "Microphone capture remains unavailable until a transcription provider is selected. This policy records explicit consent and the maximum future transcript retention; revoking consent always resets retention to none.", voiceConsent: "I consent to future microphone capture", transcriptRetention: "Maximum transcript retention", retainNothing: "Retain nothing", retainSession: "Current session only", retain24Hours: "Up to 24 hours", savePolicy: "Save voice policy", voiceCaptureEnabled: "Voice capture enabled", voiceCaptureUnavailable: "Voice capture is not implemented; microphone permission remains denied.",
    trustedCatalog: "Trusted remote catalog", reviewOnly: "review only", verifiedInstall: "verified gallery", catalogPolicy: "Catalog review is operator-triggered. HTTPS manifests must match the pinned publisher and Ed25519 key. Skill installation requires a fresh review and confirmation, then enforces the declared size and SHA-256 before safely writing a constrained text-only package with provenance. Verified hire profiles only prefill the hiring form and never launch an agent.", catalogUrl: "Catalog manifest URL", publisherId: "Pinned publisher identifier", publisherKeyId: "Pinned publisher key identifier", publisherPublicKey: "Pinned Ed25519 public key (SPKI base64)", verifying: "Verifying…", verifyCatalog: "Verify catalog", catalogEntries: "entries", cached: "cached", verified: "verified", noCatalogReviewed: "No remote catalog has been verified.", installSkillPrefix: "Install verified skill", installSkillSuffix: "from pinned publisher", installVerifiedSkill: "Install verified skill", installing: "Installing…", importVerifiedHire: "Open verified profile", importing: "Importing…",
    slackIntegration: "Slack integration", leastPrivilege: "least privilege", slackPolicy: "Bot tokens require only chat:write. Tokens are read from the clipboard by the main process, encrypted with the operating-system credential store, and never exposed to the renderer. Messages are operator-triggered; OrbiAgents does not read history, poll, impersonate users, or post in the background.", slackConfigured: "Slack configured", slackNotConfigured: "Slack is not configured.", saveSlackToken: "Save bot token from clipboard", testSlack: "Test Slack", clearSlack: "Clear Slack token", slackTokenSaved: "Slack token encrypted and saved.", slackConnected: "Slack connection verified.", slackCleared: "Slack credential cleared.", slackChannelId: "Slack channel ID", slackMessage: "Slack message", sendSlack: "Send to Slack", slackSendConfirm: "Send this message to the specified Slack channel?", slackSent: "Slack message sent.",
} as const;
export type MessageKey = keyof typeof englishMessages;
export type MessageCatalog = Record<MessageKey, string>;
const Context = createContext<{ locale: Locale; setLocale(locale: Locale): void; t(key: MessageKey): string }>({ locale: "en", setLocale: () => undefined, t: (key) => englishMessages[key] });
export function I18nProvider({ children }: { children: ReactNode }) {
  const [locale, setLocale] = useState<Locale>(() => { try { const saved = localStorage.getItem("orbiagents.locale"); return saved === "zh-CN" || saved === "ar" ? saved : "en"; } catch { return "en"; } });
  const [catalog, setCatalog] = useState<MessageCatalog>(englishMessages);
  useEffect(() => {
    document.documentElement.lang = locale; document.documentElement.dir = locale === "ar" ? "rtl" : "ltr";
    try { localStorage.setItem("orbiagents.locale", locale); } catch { /* optional */ }
    let current = true;
    if (locale === "en") setCatalog(englishMessages);
    else void (locale === "zh-CN" ? import("./locales/zh-CN") : import("./locales/ar")).then((module) => { if (current) setCatalog(module.default); });
    return () => { current = false; };
  }, [locale]);
  const value = useMemo(() => ({ locale, setLocale, t: (key: MessageKey) => catalog[key] }), [catalog, locale]);
  return <Context.Provider value={value}>{children}</Context.Provider>;
}
export function useI18n() { return useContext(Context); }
