import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";
export type Locale = "en" | "zh-CN" | "ar";
const englishMessages = {
    locale: "Interface language", help: "OrbiAgents uses only the language selected here and never reads the operating-system locale.", subtitle: "Local command deck · authenticated runtime telemetry", active: "active", hire: "Hire agent",
    commandCenter: "Command Center", operate: "Operate", coordinate: "Coordinate", observe: "Observe", system: "System",
    floor: "Floor", terminals: "Terminals", files: "Files", repository: "Repository", tasks: "Tasks", messages: "Messages", approvals: "Approvals", memory: "Memory", skills: "Skills", activity: "Activity", costs: "Costs", recovery: "Recovery", workspaces: "Workspaces", settings: "Settings", updates: "Updates", setup: "Setup",
    hireTitle: "Hire orbital agent", fleetConfiguration: "Fleet configuration", configureSpecialist: "Configure a specialist", profileRetention: "Profiles are validated and retained with the local agent session.", importHire: "Import hire", copyHire: "Copy hire", close: "Close", localGallery: "Local agent gallery", role: "Role",
    generalist: "Generalist", generalistDetail: "Balanced execution", planner: "Planner", plannerDetail: "Break down missions", builder: "Builder", builderDetail: "Implement changes", reviewer: "Reviewer", reviewerDetail: "Audit and verify", researcher: "Researcher", researcherDetail: "Investigate evidence",
    callSign: "Call sign", agentName: "Agent name", runtime: "Runtime", agentRuntime: "Agent runtime", workspace: "Workspace", workspacePath: "Agent workspace path", workspacePlaceholder: "/absolute/path/to/project", timebox: "Timebox", planningTimebox: "Agent planning timebox", minutes30: "30 minutes", hour1: "1 hour", hours2: "2 hours", hours4: "4 hours", missionGoal: "Mission goal", missionGoalLabel: "Agent mission goal", missionGoalPlaceholder: "Describe the outcome this agent owns",
    capabilities: "Capabilities", planning: "planning", coding: "coding", review: "review", research: "research", testing: "testing", signalColor: "Signal color", cyan: "cyan", violet: "violet", green: "green", gold: "gold", rose: "rose", isolatedWorktree: "Isolated worktree", useIsolatedWorktree: "Use isolated worktree", launching: "Launching…", launchAgent: "Launch agent", roleSuffix: "role", capabilitySuffix: "capability", colorSuffix: "signal color",
    hireLinkImported: "Hire link imported. Review it and choose a workspace before launching.", hireLinkCopied: "Hire link copied. Workspace paths and credentials are never included.", profileImported: "Profile imported. Review it and choose a workspace before launching.", profileSelected: "profile selected. Review before launching.",
    commandComposer: "Agent command composer", command: "Command", agentCommand: "Agent command", sendInstruction: "Send an instruction to", selectRunningAgent: "Select a running agent", queue: "Queue", workspaceAttachment: "Workspace file attachment", attachWorkspaceFile: "Attach workspace file…", attach: "Attach", remove: "Remove", queuedEncrypted: "queued · encrypted local resume", sending: "Sending…", sendAll: "Send all", filesCount: "files", retry: "Retry", send: "Send",
    agentRoster: "Agent roster", agentFleet: "Agent fleet", registered: "registered", emptyFleet: "Launch your first agent to populate the command deck.", workspaceSuffix: "workspace", agentActivity: "Agent activity", signalLog: "Signal log", liveTelemetry: "live telemetry", emptySignals: "Runtime signals will appear here.",
    selectAgentRepository: "Select an agent to inspect its workspace repository.", githubIngestion: "GitHub issue and CI ingestion", repositoryOperations: "Repository operations", inspectLocalGit: "Inspect local Git", checkGithubAuth: "Check GitHub auth", refreshGithub: "Refresh GitHub", localGitPolicy: "Local Git inspection is read-only and bounded. It never stages, commits, switches branches, or pushes.", noUpstream: "No upstream", ahead: "ahead", behind: "behind", changesCount: "changes", workingChanges: "Working changes", cleanTree: "Working tree is clean.", recentCommits: "Recent commits", noCommits: "No commits loaded.", changesTruncated: "Working changes are truncated to 200 entries.", inspectGitPrompt: "Inspect local Git to load branch, change, and commit facts.", githubPolicy: "Read-only and operator-triggered. Uses the locally authenticated gh CLI without token IPC, login automation, polling, or workflow mutation.", githubAuthenticated: "GitHub CLI is locally authenticated.", githubUnauthenticated: "GitHub CLI is not authenticated. Run gh auth login in your terminal.", githubMissing: "GitHub CLI is not installed.", fetched: "Fetched", boundedGithub: "bounded to 50 issues and 30 runs", openIssuesCount: "open issues", recentRunsCount: "recent runs", activeRunsCount: "active", attentionRunsCount: "non-success completed", showing: "showing", issuesCount: "issues", runsCount: "runs", filterIssues: "Filter issues by label", allLabels: "All loaded labels", filterRuns: "Filter workflow runs", allRuns: "All recent runs", successful: "Successful", nonSuccess: "Non-success completed", openIssues: "Open issues", noLabels: "No labels", noMatchingIssues: "No loaded issues match this label.", recentActionRuns: "Recent Actions runs", pending: "pending", noMatchingRuns: "No loaded runs match this state.", githubRefreshPrompt: "Check authentication, then explicitly refresh the selected repository.",
    welcome: "Welcome to OrbiAgents", setupPrerequisites: "Setup and prerequisites", systemReadiness: "system readiness", orbiSetup: "OrbiAgents setup", rerunChecks: "Run checks again", setupPolicy: "These checks inspect executable access and platform capabilities only. OrbiAgents will not install software, change PATH, authenticate accounts, or block access to the Command Center.", prerequisitesReady: "Core prerequisites are ready.", prerequisitesMissing: "Some core prerequisites are missing.", required: "required", optional: "optional", continueOrbi: "Continue to OrbiAgents", continueMissing: "Continue without missing tools", lastChecked: "Last checked", onboardingAcknowledged: "onboarding acknowledged",
    startupRecovery: "Startup recovery", readOnlyInventory: "read-only inventory", recoveryReport: "Startup recovery report", refreshReport: "Refresh report", recoveryPolicy: "Read-only inventory. Recovery never restarts commands, delivers tasks, changes worktrees, or decides approvals.", loadingRecovery: "Loading recovery report…", needReview: "need review.", reportTruncated: "The bounded report was truncated.", noRecoveryItems: "No interrupted sessions or unfinished durable work were detected.", inventoryGenerated: "Inventory generated",
    orbiHive: "Orbi Hive", selectHive: "Select or launch an agent to open its project Hive.", hiveOperatorPanel: "Orbi Hive operator panel", refresh: "Refresh", approvalReason: "Approval reason", rejectionReason: "Rejection reason", completedResult: "Completed task result", taskTitle: "Task title", taskForPrime: "Task for Orbi-Prime", taskDetails: "Task details", assignedAgent: "Assigned project agent", selectProjectAgent: "Select project agent", assignPrime: "Assign through Orbi-Prime", approvalsTitle: "Approvals", approve: "Approve", reject: "Reject", noApprovals: "No approvals.", primeInbox: "Prime inbox", noMessages: "No messages.", blackboard: "Blackboard", noSharedResults: "No shared results.", taskOperations: "Task operations", total: "total", actionable: "actionable", blockedCount: "blocked", waitingDependencies: "waiting on dependencies", completedCount: "completed", failedCount: "failed", retriedCount: "retried", noTasksAssigned: "No tasks assigned yet", queuedColumn: "Queued", activeColumn: "Active", blockedColumn: "Blocked", doneColumn: "Done", tasksSuffix: "tasks", unassigned: "unassigned", attempt: "attempt", start: "Start", block: "Block", complete: "Complete", noTasks: "No tasks", healthFailed: "Failed — review required", healthBlocked: "Blocked — operator action required", healthWaiting: "Waiting on dependencies", healthRetry: "Retry", healthCompleted: "Completed", healthRunning: "Running", healthReady: "Ready", noDependencies: "No dependencies", dependenciesUnresolved: "dependencies unresolved", dependenciesComplete: "dependencies complete", of: "of",
    applicationUpdates: "Application updates", installed: "installed", loading: "loading", orbiUpdates: "OrbiAgents updates", updatePolicy: "Updates are operator-controlled. OrbiAgents never checks, downloads, or restarts silently, and restart fails closed while agents, approvals, missions, or preserved workspaces require attention.", version: "Version", checking: "Checking…", checkUpdates: "Check for updates", downloading: "Downloading…", download: "Download", restartInstall: "Restart and install", updateReading: "Reading update status…", updateReadyCheck: "Ready to check", updateCheckingReleases: "Checking GitHub releases…", updateAvailable: "Update available", updateCurrent: "You are up to date", updateDownloadingPackage: "Downloading release package…", updateReadyInstall: "Update ready to install", updateFailed: "Update action failed",
    operatorApprovals: "Operator approvals", noProjectApprovals: "No approval requests for this project.", applyWorkspaceConfirm: "Apply the selected files to the clean source repository?", discardWorkspaceConfirm: "Permanently discard this preserved worktree and all of its unmerged changes?", preservedChanges: "Preserved workspace changes", changesPreserved: "Changes preserved for review", recoveryDetailsMissing: "Recovered after restart. Change details could not be refreshed automatically.", applyTrackedFile: "Apply tracked file", applyNewFile: "Apply new file", tracked: "tracked", newFile: "new", applySelected: "Apply selected", discardWorktree: "Discard worktree",
} as const;
export type MessageKey = keyof typeof englishMessages;
export type MessageCatalog = Record<MessageKey, string>;
const Context = createContext<{ locale: Locale; setLocale(locale: Locale): void; t(key: MessageKey): string }>({ locale: "en", setLocale: () => undefined, t: (key) => englishMessages[key] });
export function I18nProvider({ children }: { children: ReactNode }) {
  const [locale, setLocale] = useState<Locale>(() => { try { const saved = localStorage.getItem("orbiagents.locale"); return saved === "zh-CN" || saved === "ar" ? saved : "en"; } catch { return "en"; } });
  const [catalog, setCatalog] = useState<MessageCatalog>(englishMessages);
  useEffect(() => {
    document.documentElement.lang = locale; document.documentElement.dir = locale === "ar" ? "rtl" : "ltr";
    try { localStorage.setItem("orbiagents.locale", locale); } catch { /* optional */ }
    let current = true;
    if (locale === "en") setCatalog(englishMessages);
    else void (locale === "zh-CN" ? import("./locales/zh-CN") : import("./locales/ar")).then((module) => { if (current) setCatalog(module.default); });
    return () => { current = false; };
  }, [locale]);
  const value = useMemo(() => ({ locale, setLocale, t: (key: MessageKey) => catalog[key] }), [catalog, locale]);
  return <Context.Provider value={value}>{children}</Context.Provider>;
}
export function useI18n() { return useContext(Context); }
